version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: meu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meubanco
      MYSQL_USER: sergio
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
